### ISSUE TITLE
Some problem to works with this plugin

### ISSUE THREAD

**Issue by micker** [ttc-freebies/plugin-responsive-images#205]
hello i didn't find a good way to actived this plugin
1 i install it + override in my template
![image](https://user-images.githubusercontent.com/2539440/170975906-d8022eff-45f7-4800-9041-2eae2c12d6b2.png)
![image](https://user-images.githubusercontent.com/2539440/170975942-50081519-598f-4bda-bc2e-01d9def196f9.png)

2 in article view no change
https://proscess.org/soutiller/les-outils-de-diagnostic-de-la-promotion-de-la-sante?view=article&id=33:diagnostic-proscess&catid=12:les-outils-de-diagnostic-de-la-promotion-de-la-sante
3 in item view wit pagebuilder ck same it doesn't work
https://proscess.org/
any idea why it doesn't works ?
thanks

**Comment by dgrammatiko** [comment]
What component renders this view?

**Comment by micker** [comment]
in article view joomla : https://proscess.org/soutiller/les-outils-de-diagnostic-de-la-promotion-de-la-sante?view=article&id=33:diagnostic-proscess&catid=12:les-outils-de-diagnostic-de-la-promotion-de-la-sante)
![image](https://user-images.githubusercontent.com/2539440/171356838-133124af-ea94-4f2f-abd6-9b988ef42517.png)

here, its an joomla article view with pagebuilderck https://proscess.org/

**Comment by dgrammatiko** [comment]
@micker so it turns out that:
- there was a small bug on one conditional that's why you got the notification on line 219 (fixed with 4.1.0)
- your server doesn't have any image library (imagick of GD) which is a prerequisite for this plugin (but also for Joomla's media manager editing functionality). Check with your host how to enable either GD or imagick (preferably imagick to get AVIF support)

**Comment by micker** [comment]
ahhh i actived GD it works on article view
but no here
https://proscess.org/
internal redircetion
do you have an idea ?

**Comment by dgrammatiko** [comment]
Hmm, this might be a Joomla bug or something in my code, let me explain:

The URL of the image is:
```
https://proscess.org/media/cached-resp-images//images/pagebuilderck/informer Petit_1920.jpg?version=24be1165d9ea2d46c3976c8250a5ca53
```
With the image name: `informer Petit_1920.jpg`. The space is the one that creates the problem as it needs to be escaped (eg instead of ` ` should be `%20`)

I'll debug this later today and if it's a bug on my side I'll create a new release, if it's on Joomla's side you will need to open an issue in their repository

**Comment by micker** [comment]
ok thanks
can i disable plugin on my site ? no need for debug ?

**Comment by dgrammatiko** [comment]
You don't need the debug anymore

**Comment by micker** [comment]
thanks

**Comment by dgrammatiko** [comment]
@micker [4.1.1](https://responsive-images.dgrammatiko.dev/downloads/index.html) should fix the bug.
Thanks for reporting.
