### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ConfidantCommunications** [ttc-freebies/plugin-responsive-images#3]
Hi,
I installed and enabled the plugin and it seems to be dead. Joomla 3.8.2. No new images are created, and no folder found in the /media directory. Am I missing an image library maybe?

**Comment by cn-tools** [comment]
hi @ConfidantCommunications !

I run this code on a test system with fresh installation of Joomla! v3.8.2 and there is no additional library needed.

Is the file extension of your images uppercase?
The code - without my pull request - only support lowercase file extensions.

Is the width size of your original image greater than 360px?
Because upscaling is not implemented.

**Comment by ConfidantCommunications** [comment]
Hello, I do not use uppercase extensions, and my images are all larger than 360px wide. Perhaps plugin ordering is the problem?

**Comment by cn-tools** [comment]
Maybe ... i have placed it to the first position in section of type 'content'.

Did you visit your article in the front end view? The images are generated on-the-fly if the article will displayed the first time.

**Comment by ConfidantCommunications** [comment]
I ended up using a different solution; sorry but I don't have time to try this anymore. It is possible that cache was causing a problem.

**Comment by ConfidantCommunications** [comment]
I was using JotCache at some point.
