### ISSUE TITLE
Error message after upgrading to 4.2.2

### ISSUE THREAD

**Issue by bahman-gh858** [ttc-freebies/plugin-responsive-images#328]
Joomla: ‎4.2.5
plugin-responsive-images: 4.2.2
Plug-ins were working fine before upgrade to 4.2.2. But after upgrading, the webp images are not created and the images are displayed in original format. 
In addition, an error message appears on the screen: Image too big to be processed
But the size of the image is approximately the same as the other images

Do you have any idea what could be wrong?

Correction
If I put width and height to the intro image it works. Normally joomla should add them when you insert the image. ex:
(images/mypic.jpg#joomlaImage://local-images/mypic.jpg?width=420&height=466)

**Comment by dgrammatiko** [comment]
Could you email me the image and your settings of the plug-in? D.Grammatiko at gmail dot com

**Comment by dgrammatiko** [comment]
Could you uninstall and re install the plugin? I couldn't replicate this with the images you send me, which might be due to some file is not up to the Curren version or your server memory is low.

> If I put width and height to the intro image it works. Normally joomla should add them when you insert the image. ex:
(images/mypic.jpg#joomlaImage://local-images/mypic.jpg?width=420&height=466)

Joomla creates the correct urls for the images, I'm guessing you're using some 3rd PD editor and they are still using the old pattern (but although this is poor support from their side, the plugin should be able to fix those urls automatically). FWIW I strongly support you use the build in tinyMCE editor as some other editors are using very old versions of tinyMCE (you might have security issues with some 3rd PD editors, although the extensions directory shows that they are great [ Huge lie ])

**Comment by bahman-gh858** [comment]
I uninstalled the plugins and reinstalled it. But it did not help.
I use JCE Editor and I don't have any problem with it. Joomla creates the correct urls as image/mypic.jpg.

 I need to contact with service provider about server memory.  Because plugins work in my laptop.

**Comment by bahman-gh858** [comment]
The server has 8GB of memory. It's weird.
- I installed version 4.2.1 without success.
- I uninstalled everything (removed images) etc and reinstalled version 4.2.2, also no success.

When I check the media/cached-resp-images folder, I see that the ___data___ folder is missing. There is only the images folder, which has two empty subfolders with the names of my images.

Something on the server side is causing the problem. Plug-ins work on my laptop.
I have to troubleshoot further

**Comment by bahman-gh858** [comment]
The plugins works works well, I have no problems with it in my computer. But my service provider (one.com) seems to have problems with the plugins.  When plugins get activated, nothing happens and visitors see a error message on the screen. The error message is " Image too big to be processed".
The support does not want to troubleshoot and claims that they support webP.

**Comment by dgrammatiko** [comment]
Can you go to the backend main menu -> System
Then click on the System Information
And then on the toolbar button `Download as JSON`
A file will be exported you could attach it and send it to d.grammatiko at gmail.com

**Comment by dgrammatiko** [comment]
Should be fixed with 4.2.6, if not feel free to reopen the issue
