### ISSUE TITLE
Joomla 5 - How to make web site logo responsive?

### ISSUE THREAD

**Issue by pl71** [ttc-freebies/plugin-responsive-images#608]
Yes, how to? And how to suppress the `lazy` attribute there?
The logo image is set at Template style options.

**Comment by pl71** [comment]
Ok, I make it the same way by amending index.php. But if the plugin can do this it would be great.

**Comment by dgrammatiko** [comment]
The plugin explicitly is not doing a search and replace of all the image tags (although for most users this would have been the easier path) because there’s a performance overhead. The idea was that with Joomla 4 all developers/template authors would use the image layout for all their images but turns out this hasn’t happen yet. It’s a problem that devs are still not using the preferred and advisable way to render images because this plugin expects that or then the site admin needs to create overrides…
